### ISSUE TITLE
Deprecated providedService 1.0.0

### ISSUE THREAD

**Issue by noseglid** [bwinton/atom-build-jpm#3]
Next version of Build will no longer support the `^1.0.0` of provided services. This has been deprecated since `v0.50.0` of the build package.

[Please see the documentation to upgrade to version ^2.0.0](https://github.com/noseglid/atom-build/blob/master/create-provider.md).

**Comment by bwinton** [comment]
Fixed in c36b292d8325bd5c8e7b2c5e8cbe43446cdfcda3!
Thanks!
